all:
	g++ main.o actors.o functions.o timerclass.o resource.o -o main -lSDL -lSDL_image

most:
	g++ -c main.cpp actors.cpp functions.cpp timerclass.cpp resource.cpp

Main:
	g++ -c main.cpp

actors:
	g++ -c actors.cpp

functions:
	g++ -c functions.cpp

timerclass:
	g++ -c timerclass.cpp

resource:
	g++ -c resource.cpp
