all:
	g++ main.o actors.o functions.o timerclass.o resource.o -o main -lSDL -lSDL_image

most:
	g++ -c main.cpp actors.cpp functions.cpp timerclass.cpp resource.cpp

main.o:
	g++ -c main.cpp

actors.o:
	g++ -c actors.cpp

functions.o:
	g++ -c functions.cpp

timerclass.o:
	g++ -c timerclass.cpp

resource.o:
	g++ -c resource.cpp
